sudo: required     # anytime using docker we need to have super user permissions
services: 
   - docker

before_install:
   - docker build -t sdubey/docker-react -f Dockerfile.dev.
   
script:
   - docker run sdubey/docker-react npm run test -- --coverage