sudo: required
language: generic
branches:
 only:
 - master

services:
  - docker

if: (type == push) OR (type == pull_request AND fork == true)

before_install:
  - docker build -t sdubey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sdubey/docker-react npm run test -- --coverage
