sudo: required
language: generic
services:
  - docker

if: (type == push) 

before_install:
  - docker build -t sdubey/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sdubey/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-254618028205"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY



